<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Routing\RouteMatchInterface;

include_once('DrupalTWDocs.inc');

function twdocs_entity_delete(EntityInterface $entity) {
}

function twdocs_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if($build['body'] && $build['body'][0]) {
    $build['body'][0]["#text"] = TWDocs::$engine->render( 1, $build['body'][0]["#text"] );
  }
}

function twdocs_entity_update(EntityInterface $entity) {
}

function twdocs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.twdocs':
      $output = '<p>' . t('The TWDocs module allows a user to define a &lt;document&gt; tag that provides a semantic representation of documents.
                 The user is able to upload documents, upload new versions of that document and view the semantic information related to the document') . '</p>';
      return $output;
  }
}

